### ISSUE TITLE
Schedule - Calendar

### ISSUE THREAD

**Issue by mjleavell** [nss-evening-cohort-8/bandz-kinky-slinky#8]
### Story
As a user when I come to the schedule page I want to see a calender with event details.

### Acceptance Criteria
As a user on the schedule page I should see a month-long calender.
The calender should have listings on the relevant days for events.
The listing should include all the event information
There should be a menu to choose between months above the calender.

### Technical Details
*  Create/modify schedule.html in html/
*  Create/modify schedule.js in javascript/
*  Create calender pages for each of 3 months linked to by the menu
*  Create **dateCardSelector** function to select correct date div based on object data
*  Create **writeToDom** function to write object data to dom.
* Menu should rewrite calender div to proper month when clicked with **monthCardSelector** function.

**Comment by Rfishernc** [comment]
![bandz](https://user-images.githubusercontent.com/42363523/45334517-b2607380-b540-11e8-8b11-55d1bc41db94.PNG)
